package com.iwt.services;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserInfoDelegate", targetNamespace = "http://services.iwt.com/")
public interface UserInfoDelegate {

    /**
     * 
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://services.iwt.com/", className = "com.iwt.services.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://services.iwt.com/", className = "com.iwt.services.GetUserInfoResponse")
    public String getUserInfo();

}
